apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: dWh5N25hcWM=
  CLOUDINARY_KEY: OTY3MTQyNDc4OTgyMzMz
  CLOUDINARY_SECRET: ek9BLUhBdXprcllhamxZZmxlWHVWMlNyQXJz
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lhMlZ6YUdGMllUa3hNREFpTENKaElqb2lZMjEwYlhob2NUYzNNR04zYkRKNWN6Y3hNVzUyWTJjMGNTSjkuVmZqcFdRRlB4UDktX1F2cXhjMGNzZw==
  DB_URL: bW9uZ29kYitzcnY6Ly9hbmRla2VzaGF2YV9kYl91c2VyOmFMWDVJSHhGVlFYdDNiVkRAY2x1c3RlcjAuODlsbWtqYy5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==
